### ISSUE TITLE
Idea: `brew history` to show command history

### ISSUE THREAD

**Issue by liudangyi** [Homebrew/Outreachy-and-Google-Summer-of-Code#1]
I'd like to add a new command `brew history`, just like [`dnf history`](http://dnf.readthedocs.org/en/latest/command_ref.html#history-command-label). It would be useful if a user wants to uninstall a package with its dependencies that are installed together (homebrew/homebrew#7465). Also, users may check which package was upgraded / uninstalled at which time and partially undo the transaction. 

It's only a preliminary idea. I would like to know whether it'll be considered helpful, or totally useless. Thank you.

**Comment by mikemcquaid** [comment]
Hi @liudangyi! That's a cool idea but I think having a separate command would not be the best implementation in the long-term. What would be required for this is for package installation to log whether it was installed as a dependency or manually (and provide a way for you to "upgrade" that e.g. perhaps if you manually `brew install` the dependency) in the `INSTALL_RECEIPT.json` and then make use of that in a `brew history-uninstall` command until it was ready to be included in Homebrew and then make it part of the `uninstall` command.

I think this is an interesting enough project that, given a good, well-researched proposal, we'd consider accepting it :+1:

**Comment by liudangyi** [comment]
I've realized It'd be much easier if we only want to resolve dependency problem. Just add a new item `installed_as_dependency` to `INSTALL_RECEIPT.json`. Then add a new command `brew auto-remove` to recursively remove all leaf packages that are `installed_as_dependency`.

So it seems not so useful to provide `brew history` if we only want to `uninstall --auto-remove`.

**Comment by mikemcquaid** [comment]
@liudangyi Yep, I agree. This could even be handled by `brew cleanup`. I'd suggest this code lives in an external command to start with; that'll make it easier for you to work on and test without changing Homebrew core. If you haven't already: make some trivial (e.g. brew audit fix) PRs to Homebrew before submitting your proposal so you're familiar with how our PR process works but otherwise: sounds great :+1:

**Comment by liudangyi** [comment]
Thank you for your advice. I'll try to make some PRs next. 

Another question: will this work be too trivial to be a GSoC project? Since the estimated line of codes won't be too much. Should I combine some other improvements in the proposal?

**Comment by mikemcquaid** [comment]
I think getting this change high quality and integrated into Homebrew would be enough of a project. If you get all that done: we can find other things to do :grinning:

**Comment by mikemcquaid** [comment]
Unfortunately this project was not accepted in the GSoC or Outreachy 2016.
