### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by DrAwkward2592** [Homebrew/Outreachy-and-Google-Summer-of-Code#2]
Hi @mikemcquaid, this is Adityan. We talked over the mailing list. Can you tell me more about the API documentation project? Which APIs need more documentation? Can you describe the details of what you are looking to get done in this project?

**Comment by vdjeudjam** [comment]
Hi @mikemcquaid , I am Veranew and i want to participate to the outreachy internship program with Homebrew. I am interested in the API documentation project. How do i get started? Any mailing list, irc, etc Can i have more details about the project?

**Comment by mikemcquaid** [comment]
Hi!

http://www.rubydoc.info/github/Homebrew/homebrew/master/ is the current location of our API documentation. The `Formula` class is mostly documented but there's some other public APIs that are not currently fully documented and some classes in there that are public but should not be. The goal of this project would be to document those parts that are missing and hide those parts that should not be public so we have a fully documented, public, stable API for a 1.0.0 release.

Does that help to explain things? Please ask more questions if not.

In terms of how best to get started: run `brew audit` in Homebrew and submit a pull request fixing one of those audit warnings in an existing formula.

Thanks!

**Comment by mikemcquaid** [comment]
Unfortunately this project was not accepted in the GSoC or Outreachy 2016.
