### ISSUE TITLE
Emit warnings for mistyped options.

### ISSUE THREAD

**Issue by i-freelancer** [Homebrew/Outreachy-and-Google-Summer-of-Code#3]
Hi @mikemcquaid , 
I want to work on 'Emit warnings for mistyped options' as my GSoc project.I have experience in Ruby,C++,Bash,Python.
I looked up the issue page(https://github.com/Homebrew/homebrew/issues/8937) and have some confusions as how to start with the issue.Any help will be great. :)

**Comment by mikemcquaid** [comment]
Hi!

The best place to start would be building all the valid options for `brew install` for a particular formula and warning if any additional options are passed.

**Comment by mikemcquaid** [comment]
Also: in terms of how best to get started: run brew audit in Homebrew and submit a pull request fixing one of those audit warnings in an existing formula.

**Comment by mikemcquaid** [comment]
Unfortunately this project was not accepted in the GSoC or Outreachy 2016.
