### ISSUE TITLE
Improve brew tests coverage percentage by writing more tests

### ISSUE THREAD

**Issue by avaldivi** [Homebrew/Outreachy-and-Google-Summer-of-Code#4]
Hello @mikemcquaid ,
My name is Adrianna. I am applying for the Outreachy Internship and I am interested in writing more tests as my contribution for Homebrew. I have experience writing mini-tests for mini projects in my college course but that may not be enough. I was researching on how I can access the different integration tests already created to get a look at what I could be working with. The only thing I came across was your discussion with another member if you have a 'How-to' doc on writing core tests.

 https://github.com/Homebrew/homebrew/issues/41326

If I can get more information on how to access the integration/core tests already created that would be great. I would also like to suggest if I stay with this Idea of Contribution to Homebrew, could I suggest in creating a 'How-to' doc on creating core tests if it is needed. Pardon my little knowledge of anything. I have installed Homebrew using 'brew.sh' and 'brew audit' to review or access any familiar warnings.

Thank you.

**Comment by bfontaine** [comment]
Hi Adrianna,
All the tests are located under [`Library/Homebrew/test`](https://github.com/Homebrew/homebrew/tree/master/Library/Homebrew/test). Homebrew is installed in `/usr/local` so you should be able to go in this directory on your computer with `cd /usr/local/Library/Homebrew/test`.
Files that contain tests start with `test_`. Methods starting with `test_` are unit tests.

The integration tests are in the [`test_integration_cmds.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/test/test_integration_cmds.rb) file. They use a helper method called [`cmd`](https://github.com/Homebrew/homebrew/blob/569c4105a3e2764ddbb7191c6bcb0cf7cc682a73/Library/Homebrew/test/test_integration_cmds.rb#L66) that runs a `brew` command in a separate process and retrieves its output. You can ensure that e.g. `brew foo bar` prints `hello` by using `assert_match "hello", cmd("foo", "bar")`.

You can run the whole tests suite with `brew tests`. Add `--verbose` for a more verbose output. You can run the tests in one file only by using `--only=<file>` where `<file>` is the part of the filename after `test_`: `test_<file>.rb`. You can also run only one test by using `--only=<file>/<method>`; `<method>` is the part of the method name after `test_`, e.g. `brew tests --only=json/encode` will run the test defined in the method `test_encode` located in the `test_json.rb` file.

Add `--coverage` to get the tests code coverage. You can then open `Library/Homebrew/test/coverage/index.html` in your browser to have an overview.

Feel free to ask any question if something is unclear!

**Comment by mikemcquaid** [comment]
> Add --coverage to get the tests code coverage. You can then open Library/Homebrew/test/coverage/index.html in your browser to have an overview.

@avaldivi This is the crucial bit you may want to play around with as any new tests you add will be to increase this coverage percentage. Shout if you have any more questions!

Also, in terms of how best to get started with Homebrew: run `brew audit` in Homebrew and submit a pull request fixing one of those audit warnings in an existing formula. Thanks!

**Comment by mikemcquaid** [comment]
@avaldivi Also: shout here or at mike@mikemcquaid.com if you have any other questions. Would really like to see you apply here! If you haven't already considered you may want to also apply for Google Summer of Code too.

**Comment by avaldivi** [comment]
@bfontaine @mikemcquaid thank you for responses. I will be applying hoping for enough time to work on it before applications are due March 22nd.

**Comment by mikemcquaid** [comment]
@avaldivi Great, thanks!

**Comment by eirinikos** [comment]
Hi @avaldivi, thanks for opening this issue; it answered a lot of questions I've had this week.

Questions for @mikemcquaid and @bfontaine or anyone else who's able to answer:
Perhaps this will betray how much more I need to learn about testing -
When I look at the coverage info for the `brew doctor` command (for example), it shows exactly which lines are covered by tests and which aren't covered, yes? Where would I find the tests that provide the coverage that exists for `doctor.rb`? Also, what are the numbers at the end of each green line in the coverage report?

Thanks!

![screen shot 2016-03-17 at 11 24 55 pm](https://cloud.githubusercontent.com/assets/9170701/13870013/bf35c4c6-ec97-11e5-8f3f-a35e4956cc07.png)

**Comment by mikemcquaid** [comment]
> When I look at the coverage info for the brew doctor command (for example), it shows exactly which lines are covered by tests and which aren't covered, yes?

Correct! It's using `simplecov` to generate that if that helps your research.

> Where would I find the tests that provide the coverage that exists for doctor.rb? 

https://github.com/Homebrew/homebrew/blob/a8b1669e3bea70647f469b997741ee45638f3267/Library/Homebrew/test/test_integration_cmds.rb#L254-L257 In general they will all be in the `Library/Homebrew/test` directory.

> Also, what are the numbers at the end of each green line in the coverage report?

**Comment by bfontaine** [comment]
> Also, what are the numbers at the end of each green line in the coverage report?

This is the number of time each line was covered.

**Comment by eirinikos** [comment]
Thanks, @bfontaine and @mikemcquaid! I'll report back in the next few days if I've any new questions. :)

**Comment by eirinikos** [comment]
Hello again! Question:

Running `brew tests --only=integration_cmds/doctor --coverage` returns (among other things):
`Coverage (13.28%) is below the expected minimum coverage (40.00%).`

But the coverage overview in `Library/Homebrew/test/coverage/index.html` shows that coverage for `Homebrew/cmd/doctor.rb` is 74.07%. I'm sure there's an explanation, but I don't know what it is... what is it?

**Comment by mikemcquaid** [comment]
@eirinikos Hi! When you do `--only=` you'll end up getting a coverage number that's only for that specific test so it's expected that it'll be under the minimum coverage as that's for the entire codebase (as you noticed) rather than for individual files. In this case the integration test ends up calling more than just `doctor` as it calls out to other code too. Hopefully that helps, shout if it does not!

**Comment by mikemcquaid** [comment]
@eirinikos Was accepted to Outreachy 2016 for this project 🎉
