### ISSUE TITLE
Help with GSoC submission

### ISSUE THREAD

**Issue by miguelarauj1o** [Homebrew/Outreachy-and-Google-Summer-of-Code#5]
Hello, I'm considering the possibility of applying to GSoC, but I don't have experience in Ruby. So, I can't measure how difficult each idea described in README is. Therefore, I need help.

**Comment by mikemcquaid** [comment]
Hi @miguelarauj1o! You'll need to elaborate a bit more on what help you need and what in the README isn't clear?

**Comment by miguelarauj1o** [comment]
Hey @mikemcquaid, sorry I wasn't 100% clear.
I have never worked with Ruby, but I know Git. Thus, I need your help to select a idea not too hard.

**Comment by mikemcquaid** [comment]
@miguelarauj1o I think selecting an idea and assessing relative difficult is part of the application process so I'm unable to do it for you, sorry.

**Comment by miguelarauj1o** [comment]
yeah, I agree. Thanks!
