### ISSUE TITLE
Cache subdirectories for formulae and versions for speedup

### ISSUE THREAD

**Issue by harshnarang8** [Homebrew/Outreachy-and-Google-Summer-of-Code#7]
Hi @MikeMcQuaid !
 I have a few queries regarding the Homebrew Cache project and some general questions.
- I have been working on some very trivial bugs and warnings in a few formulae. It'd would be great if you could point me to tasks which would help me get familiar with the Homebrew Cache.
- It would be a great help if you could point me to some documentation related to brew's codebase. I've tried going through the user docs, man page, but could not find the required stuff.
- Also, I'd really like if you could submit feedback on my draft proposal.

Update: I'm trying to go through files which contain `HOMEBREW_CACHE`, so if there is a better way to approach the task, please mention the approach; as it would enable me to formulate my to-do list in a better way.

**Comment by MikeMcQuaid** [comment]
> I have been working on some very trivial bugs and warnings in a few formulae. It'd would be great if you could point me to tasks which would help me get familiar with the Homebrew Cache.

Sure thing but lets wait until those PRs are opened, reviewed and merged first.

> It would be a great help if you could point me to some documentation related to brew's codebase. I've tried going through the user docs, man page, but could not find the required stuff.

I'm afraid all we have is http://docs.brew.sh and http://www.rubydoc.info/github/Homebrew/brew/master/Formula.

> Also, I'd really like if you could submit feedback on my draft proposal.

Sure. Email me at mike@mikemcquaid.com

**Comment by harshnarang8** [comment]
@MikeMcQuaid I've finished up with getting the PRs merged. They are minor audit fixes really, so I haven't had an opportunity to go for a related task.

**Comment by MikeMcQuaid** [comment]
@harshnarang8 Where are the PRs? Can you link me to them?

**Comment by harshnarang8** [comment]
https://github.com/Homebrew/homebrew-science/pull/5226
https://github.com/Homebrew/homebrew-science/pull/5224
@MikeMcQuaid These got merged then, while one is pending.
https://github.com/Homebrew/homebrew-science/pull/5230

**Comment by MikeMcQuaid** [comment]
@harshnarang8 Great, thanks! Could you try to submit one to homebrew/core too?

**Comment by harshnarang8** [comment]
Sure! But is a minor fix okay, or should I try something more involved?

**Comment by MikeMcQuaid** [comment]
Minor fix is OK but the more involved the better.

**Comment by MikeMcQuaid** [comment]
> I'm trying to go through files which contain HOMEBREW_CACHE

This seems sensible 👍

**Comment by harshnarang8** [comment]
@MikeMcQuaid I have made a preliminary outline, and have a few questions:
Link to document: [https://docs.google.com/document/d/1e-AKyt0oHvcmVwHJ5-dCz_Z2Mrk9XOx82SXdaGCkshQ/edit?usp=sharing](url)

P.S. Sorry for reply late, could not access internet for the last week.

**Comment by MikeMcQuaid** [comment]
@harshnarang8 We'll need a significantly more in-depth outline of your planned work. Do you mind asking the specific questions you want me to answer in here? I wasn't sure from the document. Thanks!

**Comment by harshnarang8** [comment]
@MikeMcQuaid I agree with you. This is not a proposal, I'm working out the finer details.
- (Need Confirmation) For changing the structure of the cache, will a script called by `brew update` do the job?
- (Need Confirmation) All the relevant scripts have to be updated to follow the directory structure.
- What exactly does speeding up `brew cleanup` mean? I think it refers to as follows, deleting the second oldest versions (and later too) in faster time, which are present in the HOMEBREW_CACHE. Deleting a found item is a constant process, which means that speeding could essentially be implemented in the way the files are found.

**Comment by MikeMcQuaid** [comment]
> For changing the structure of the cache, will a script called by brew update do the job?

Yes. This should live in `brew update-report` and be written in Ruby.

> All the relevant scripts have to be updated to follow the directory structure.

I don't understand the question. Which scripts? If you mean "all of Homebrew" then: yes.

> What exactly does speeding up brew cleanup mean? I think it refers to as follows, deleting the second oldest versions (and later too) in faster time, which are present in the HOMEBREW_CACHE. Deleting a found item is a constant process, which means that speeding could essentially be implemented in the way the files are found.

Trying to make the implementation such that a no-op (i.e. no files are removed) is run in under a second and therefore we can run `brew cleanup` automatically after e.g. every `brew install`.

**Comment by harshnarang8** [comment]
@MikeMcQuaid I've prepared [a timeline](https://docs.google.com/document/d/17IdNbThd3TIxxZy9JNS1Fs5GrFaSvGDf4tgj9OD2Au0/edit?usp=sharing) for the project. Please review the same.
Also, I've been working on [a document](https://docs.google.com/document/d/1PdGrO4qmMgzkPiaycV4D0eBQtkvJmRs3HU1_pBGh5EY/edit?usp=sharing), a list of files concerned with the Homebrew Cache. Please check this out, and I'd love to hear your reviews about the same.
P.S. Please ignore the comments in the file (text after // in the document, each line), as it was usually a preliminary look at the mentioned scripts.

**Comment by MikeMcQuaid** [comment]
@harshnarang8 Please write up a full proposal and I'll review that alongside a timeline. It may be easier/better to email me directly at mike@mikemcquaid so I can provide private feedback.

> Also, I've been working on a document, a list of files concerned with the Homebrew Cache. Please check this out, and I'd love to hear your reviews about the same.

I don't understand what you're asking me here, sorry. Please be much more explicit.

**Comment by harshnarang8** [comment]
@MikeMcQuaid I'd really like you to check out the document and point out if I've missed some major directories or files which depend on the cache.

**Comment by MikeMcQuaid** [comment]
@harshnarang8 You can search just for the usage of `HOMEBREW_CACHE`.

**Comment by denji** [comment]
We could use [Zstandard](http://facebook.github.io/zstd/) with the dictionary deduplication & compress `HOMEBREW_CACHE`?

**Comment by harshnarang8** [comment]
@denji, I'm not sure how compressing the `HOMEBREW_CACHE` would help achieve faster speeds for cleanup. Could you please elaborate on the same?

**Comment by MikeMcQuaid** [comment]
GSoC applications are underway so closing.
