### ISSUE TITLE
GSoc: Emit warnings for mistyped options (https://github.com/Homebrew/brew/issues/1860)

### ISSUE THREAD

**Issue by raza15** [Homebrew/Outreachy-and-Google-Summer-of-Code#8]
Hi @MikeMcQuaid !

1. I have submitted some trivial PRs to Homebrew to get familiar with the project and also to get started. I have been using Homebrew for some time now and I really like how easy it makes the life of mac users :) 

2. I am planning on applying to Google Summer of Code (GSoc) and/or Outreachy internship. Will it hurt my chances of getting selected if I apply to both of them? (I saw the answer to this question from last year but was wondering what was the case this year). And can I use the same project proposal and idea for both of them? 

3. If I send my proposal draft for review, would you give me some feedback?

Thanks.

**Comment by raza15** [comment]
Here are my accepted PRs on ```homebrew-core```:
https://github.com/Homebrew/homebrew-core/pull/11600
https://github.com/Homebrew/homebrew-core/pull/11599
https://github.com/Homebrew/homebrew-core/pull/11560
https://github.com/Homebrew/homebrew-core/pull/11541

And this one is currently under review on ```brew```:
https://github.com/Homebrew/brew/pull/2393

**Comment by MikeMcQuaid** [comment]
@raza15 Thanks for the kind words and nice work on the PRs! We're not doing Outreachy this year. Please feel free to email me at mike@mikemcquaid.com your proposal so we can talk about it. Thanks!

**Comment by raza15** [comment]
Thanks!

**Comment by raza15** [comment]
Hey @MikeMcQuaid. I really like this project: ```Port brew audit rules to RuboCop``` Can you please tell me if anyone has already selected this one? My other choice is ```Emit warnings for mistyped options ```

Thanks.

**Comment by MikeMcQuaid** [comment]
@raza15 We already have someone who has submitted multiple PRs for that so it would not be the best pick, I think. You may want to email me privately with a proposal document for `Emit warnings for mistyped options` and I can review it. Thanks!

**Comment by raza15** [comment]
Hi @MikeMcQuaid. I have a few questions for ```Emit warnings for mistyped options ```. I hope asking the questions here is ok (please tell me if its not).
So, I was looking at the source code and noticed a few things:
In file ```/usr/local/Homebrew/Library/Homebrew/cmd/options.rb ```, the code explicitly caters to the all possible options that can be supplied with the ``` brew options ``` command, such as: ``` brew options --installed ```. If I type ``` brew options --ins ``` for example, it displays a nice error message that the command is invalid. 
I believe this is what we should do for other ```brew ``` commands such as ``` brew cleanup ```. For example, for the ``` brew cleanup ``` command, we can check for each possible option that is valid for that command, and if not, raise an exception. 
Correct me if i'm wrong. 

Thanks.

**Comment by raza15** [comment]
However, there are some bugs in ``` options.rb ```. The command will run if
(1) A formula is provided with an invalid option, e.g: ```brew options latex2html --someString ```
(2) A valid option is provided with an invalid option, e.g: ``` brew options --installed --someString ```
In my opinion, these above 2 commands should not be running and be instead giving a error message that an invalid option is provided.

**Comment by raza15** [comment]
For the Homebrew command ``` commands ```, I have tried to ``` Emit warnings for mistyped options  ``` in this PR: https://github.com/Homebrew/brew/pull/2420

**Comment by MikeMcQuaid** [comment]
> hope asking the questions here is ok (please tell me if its not).

Fine with me!



> I believe this is what we should do for other brew commands such as brew cleanup. For example, for the brew cleanup command, we can check for each possible option that is valid for that command through ARGV.include?, and if a supplied option is not valid, raise an exception. I believe this has to be done for every Homebrew command listed in /usr/local/Homebrew/Library/Homebrew/cmd/ directory. (And is this what you mean when you said implementing a new DSL for Homebrew commands ?)

Yep, this is correct!



> However, there are some bugs in options.rb.

If so, fixing them would be great too.

**Comment by raza15** [comment]
Awesome! Thanks!

**Comment by MikeMcQuaid** [comment]
GSoC applications are underway so closing.
